server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guardian
    username: guardian
    password: t7q4e8qh
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#        dialect: PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

guardian:
  membership:
    default-page-size: 30
